# Generated by Django 4.1.7 on 2023-04-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GrauParentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Morada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero_casa', models.IntegerField(default=0)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoDesaparecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=200)),
                ('morada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.morada')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Desaparecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desaparecimento', models.DateField()),
                ('foto', models.CharField(max_length=200)),
                ('observacao', models.CharField(max_length=200)),
                ('deficiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.deficiencia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.estado')),
                ('motivo_desaparecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.motivodesaparecimento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoDesaparecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parente', models.CharField(max_length=200)),
                ('numero_telefone_1', models.IntegerField()),
                ('numero_telefone_2', models.IntegerField()),
                ('desaparecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.desaparecimento')),
                ('grau_parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.grauparentesco')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='bairro',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.comuna'),
        ),
    ]
